### ISSUE TITLE
Consider changing Git branch name scheme to be PEP440 compliant

### ISSUE THREAD

**Issue by odscjames** [openownership/bods-dev-handbook#13]
https://www.python.org/dev/peps/pep-0440/ 

This means that we can use the "warning banner on old versions" feature in Read The Docs in the future.

**Comment by stevenday** [comment]
I looked into this today, I think the process would be:

- [ ] Create new branches with the right names (0.2.0, 0.1.0, 0.0.3, 0.0.2, 0.0.1) by branching off the existing ones
- [ ] Enable those branches in read the docs and build them (note you need to manually run a build of *something* to pick up new branches which don't have any new commits)
- [ ] Set up [exact redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects) in the RTD admin along the lines of: `/en/v0-2-0/$rest` -> `/en/0.2.0/` (one for each version, plus one for the languages we've already published content under, e.g. `/ru/v0-2-0/$rest` -> `/ru/v0.2.0/`. Only v0-2-0 has other languages than `en`. Note that after testing, the `$rest` works for every page except the root, which needs a dedicated redirect as well 
- [ ] Set the [default version and default branch](https://readthedocs.org/dashboard/beneficial-ownership-data-standard/advanced/) to `0.2.0` instead of `v0-2-0`.
- [ ] Disable the old branches in read the docs
- [ ] Remove the manually added old version links in v0-0-1, 2 and 3 (v0-1's is disappearing anyway in https://github.com/openownership/data-standard/pull/305)
- [ ] Update this documentation to use the new branch scheme names and links
- [ ] Update any outstanding PRs to rebase them onto the right branches
- [ ] (Eventually) delete the old branches in github

I've run a test with v0-0-1 and v0-0-2 now to make sure this works as expected, which I'll leave up for someone else to confirm. It's slightly flawed in that 0.0.1 points to 0.0.2 as the latest, since rtd doesn't recognise any others, but I don't that matters for a few days.

@Bjwebb / @odscjames - would one of you have time to look at this list and double check I haven't missed anything? If not, I'll make these changes next week. In particular, I'm wondering if the original naming scheme was chosen for any particular reason, and if we need to do anything in our custom theme? (I don't think so on the latter, though we may want to add some css to style it better?).

**Comment by Bjwebb** [comment]
@stevenday I've glanced through the list, and it looks good. @odscjames might want to take a look too.

**Comment by stevenday** [comment]
I've done almost all these steps today, except for updating the docs and deleting old branches (there are no outstanding PRs against them). I had to do these a bit unilaterally because after I deployed the theme changes for the standard, I ended up with some stale read the docs versions that no other options seemed to fix. I'll add a PR for the docs in a moment to close this off.
